RESET MASTER;

ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';

CREATE USER IF NOT EXISTS 'repl'@'%' IDENTIFIED BY 'repl' REQUIRE SSL;
GRANT RELOAD, PROCESS, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'repl'@'%';

FLUSH PRIVILEGES;

CREATE USER IF NOT EXISTS 'anonymous_api'@'%' IDENTIFIED BY 'anonymous_api' REQUIRE X509;
GRANT ALL ON traylme.* TO 'anonymous_api'@'%';

FLUSH PRIVILEGES;

FLUSH TABLES WITH READ LOCK;

UNLOCK TABLES;
