version: '3.8'
services:
  mysql-master:
    image: mysqlx
    container_name: mysql-master
    command: /bin/bash -c '/data/scripts/master.sh && mysqld_safe --user=mysql --server-id=1'
    ports:
      - 3306:3306
    networks:
      - database

  mysql-slave:
    image: mysqlx
    container_name: mysql-slave
    command: /bin/bash -c '/data/scripts/slave.sh mysql-master && mysqld_safe --user=mysql --server-id=2'
    ports:
      - 3307:3306
    depends_on:
      - mysql-master
    networks:
      - database

  adminer:
    image: adminer
    ports:
      - 8088:8080
    networks:
      - database
    links:
      - mysql-master:db

  adminer_slave:
    image: adminer
    ports:
      - 8089:8080
    networks:
      - database
    links:
      - mysql-slave:db

networks:
  database:
